.init_build_gem: &init_build_gem |

  function enable_gemstash_key() {
    mkdir -p ~/.gem && touch ~/.gem/credentials && chmod 0600 ~/.gem/credentials
    echo "---" >> ~/.gem/credentials
    echo :gemstash_gitlab: $BUNDLE_GEMSTASH_PASSWORD >> ~/.gem/credentials
  }

  function build_gem() {
    enable_gemstash_key

    GIT_TAG=$(git describe --tags)

    if [[ $GIT_TAG =~ [-] ]]; then
      VERSION_NO=$(echo $GIT_TAG | cut -d '-' -f 1,2 | sed "s/[-]/./g")
      VERSION_NO+="."
      VERSION_NO+=$(date +%s)
    else
      VERSION_NO=$GIT_TAG
    fi

    echo $VERSION_NO > version

    gem build *.gemspec

    for i in *.gem; do gem push --key gemstash_gitlab --host $BUNDLE_GEMSTASH_HOSTNAME  $i; done
  }

build_gem: &build_gem
  stage: build
  image: ruby:2.5.1
  before_script:
    - *init_build_gem
  script:
    - build_gem
  only:
  - tags

manual_build_gem:
  <<: *build_gem
  only:
    - branches
  before_script:
    - *init_build_gem
  except:
    - master
  when: manual