# Auto DevOps
# Almost like https://raw.githubusercontent.com/gitlabhq/gitlabhq/master/vendor/gitlab-ci-yml/Auto-DevOps.gitlab-ci.yml but only the parts we want

variables:
  POSTGRES_USER: user
  POSTGRES_PASSWORD: testing-password
  POSTGRES_ENABLED: "true"
  POSTGRES_DB: $CI_ENVIRONMENT_SLUG

# rubycritic
code_quality:
  extends: .cache
  stage: analysis
  image: ruby:2.5.1
  allow_failure: true
  script:
    - export GEM_HOME=.cache/
    - gem install rubycritic
    - .cache/bin/rubycritic --no-browser
  artifacts:
    expire_in: 1 month
    paths: [tmp/rubycritic/*]
  only:
    refs:
      - branches
    variables:
      - $CODE_QUALITY_ENABLED

# brakeman
brakeman:
  extends: .cache
  stage: analysis
  image: ruby:2.5.1
  allow_failure: true
  script:
    - export GEM_HOME=.cache/
    - gem install brakeman
    - .cache/bin/brakeman --format json --force-scan --run-all-checks --quiet | tee brakeman.json || true
  artifacts:
    expire_in: 1 month
    paths: [brakeman.json]
  only:
    refs:
      - branches
    variables:
      - $BRAKEMAN_ENABLED

# brakeman/find-sec-bugs/NodeJsScan
sast:
  stage: analysis
  image: docker:stable
  variables:
    DOCKER_DRIVER: overlay2
  allow_failure: true
  services:
    - docker:stable-dind
  script:
    - setup_docker
    - sast
  artifacts:
    expire_in: 1 month
    paths: [gl-sast-report.json]
  only:
    refs:
      - branches
    variables:
      - $SAST_ENABLED

dast:
  stage: analysis
  image: docker:stable
  variables:
    DOCKER_DRIVER: overlay2
  allow_failure: true
  services:
    - docker:stable-dind
  script:
    - setup_configs
    - docker login --username=$DOCKERHUB_USER --password=$DOCKERHUB_PASSWORD
    - docker run -d --network host -p $DAST_ON_PORT:$DAST_ON_PORT -v $CI_PROJECT_DIR/config:/app/config $DOCKERHUB_GROUPNAME/$CI_PROJECT_NAME:$CI_BUILD_REF_NAME
    - docker run -t owasp/zap2docker-stable zap-baseline.py -t http://127.0.0.1:$DAST_ON_PORT
  artifacts:
    paths: [gl-dast-report.json]
  only:
    refs:
      - master
    variables:
      - $DAST_ENABLED
      - $DAST_PORT

# bundler-audit
dependency_scanning:apps:
  extends: .cache
  stage: analysis
  allow_failure: true
  script:
    - export GEM_HOME=.cache/
    - grep "ruby " Gemfile > current_ruby_version.txt
    - gem install bundler bundler-audit
    - .cache/bin/bundler-audit check --update | tee bundler_audit.txt || true
    - .cache/bin/bundler outdated --parseable | tee bundler_outdated.txt || true
    - wget --quiet -O - https://www.ruby-lang.org/en/downloads/releases/ | grep '<td>Ruby' | cut -d ">" -f 2 | grep '</td' | grep -v preview | cut -d "<" -f 1 | cut -d " " -f 2 | grep -v rc | sort | awk -v x=$(cat current_ruby_version.txt | cut -d " " -f 2 | cut -d "'" -f 2) '$1 > x' | sed -e 's/$/ new Ruby version available/' > new_ruby_versions.txt
  artifacts:
    expire_in: 1 month
    paths:
      - bundler_audit.txt
      - bundler_outdated.txt
      - new_ruby_versions.txt
  only:
    refs:
      - branches
    variables:
      - $DEPENDENCY_SCANNING_ENABLED
  except:
    variables:
      - $YES_THIS_IS_THE_APPS_GROUP == null

dependency_scanning:gems:
  extends: .cache
  stage: analysis
  image: ruby:2.5.1
  allow_failure: true
  script:
    - export GEM_HOME=.cache/
    - bundle install --jobs $(nproc) --path=$CACHE_LOCATION
    - gem install bundler bundler-audit
    - .cache/bin/bundler-audit check --update | tee bundler_audit.txt || true
    - .cache/bin/bundler outdated --parseable | tee bundler_outdated.txt || true
  artifacts:
    expire_in: 1 month
    paths:
      - bundler_audit.txt
      - bundler_outdated.txt
  only:
    refs:
      - branches
    variables:
      - $DEPENDENCY_SCANNING_ENABLED
  except:
    variables:
      - $YES_THIS_IS_THE_GEMS_GROUP == null

# clair
container_scanning: &container_scanning
  stage: analysis
  image: docker:stable
  variables:
    DOCKER_DRIVER: overlay2
  allow_failure: true
  services:
    - docker:stable-dind
  script:
    - setup_docker
    - container_scanning
  artifacts:
    expire_in: 1 month
    paths: [gl-container-scanning-report.json]
  only:
    refs:
      - stage
      - prod
    variables:
      - $CONTAINER_SCANNING_ENABLED

manual_container_scanning:
  <<: *container_scanning
  only:
    - branches
  except:
    - master
    - dev
  when: manual

# git secrets / trufflehog
git_secrets_scanning:
  stage: analysis
  image: docker:stable
  variables:
    DOCKER_DRIVER: overlay2
  allow_failure: true
  services:
    - docker:stable-dind
  script:
    - setup_docker
    - docker run -v $CI_PROJECT_DIR:/git mojdigitalstudio/git-secrets-ahoy --json | tee trufflehog.txt || true
  artifacts:
    expire_in: 1 month
    paths: [trufflehog.txt]
  only:
    refs:
      - branches
    variables:
      - $GIT_SECRETS_SCANNING_ENABLED

analysis_report:
  stage: analysis_report
  image: ruby:2.5.1
  script:
    - gem install project_support -v 2.0.8.5.g1c4be45 --source https://$BUNDLE_GEMSTASH_PASSWORD@$BUNDLE_GEMSTASH_HOST
    - ai_report_issues -t bundler_outdated -i bundler_outdated.txt
    - ai_report_issues -t ruby_version -i new_ruby_versions.txt
    - ai_report_issues -t brakeman -i brakeman.json
  dependencies:
    - code_quality
    - brakeman
    - sast
    - dast
    - dependency_scanning:apps
    - dependency_scanning:gems
    - container_scanning
    - git_secrets_scanning


# ---------------------------------------------------------------------------

.auto_devops: &auto_devops |
  # Auto DevOps variables and functions
  [[ "$TRACE" ]] && set -x
  auto_database_url=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${CI_ENVIRONMENT_SLUG}-postgres:5432/${POSTGRES_DB}
  export DATABASE_URL=${DATABASE_URL-$auto_database_url}
  export CI_APPLICATION_REPOSITORY=$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG
  export CI_APPLICATION_TAG=$CI_COMMIT_SHA
  export CI_CONTAINER_NAME=ci_job_build_${CI_JOB_ID}
  export SP_VERSION=$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')

  function sast() {
    docker run --env SAST_CONFIDENCE_LEVEL="${SAST_CONFIDENCE_LEVEL:-3}" \
               --volume "$PWD:/code" \
               --volume /var/run/docker.sock:/var/run/docker.sock \
               "registry.gitlab.com/gitlab-org/security-products/sast:$SP_VERSION" /app/bin/run /code
  }

  function setup_configs() {
    echo 'Using config/*.yml.example to prepare config/*.yml...'
    for file in `ls config/*.yml.example`; do
      cp $file ${file%%.*}.yml
    done
  }

  function container_scanning() {
    docker run -d --name db arminc/clair-db:latest
    docker run -p 6060:6060 --link db:postgres -d --name clair --restart on-failure arminc/clair-local-scan:v2.0.1
    apk add -U wget ca-certificates

    docker login --username=$DOCKERHUB_USER --password=$DOCKERHUB_PASSWORD
    docker pull $DOCKERHUB_GROUPNAME/$CI_PROJECT_NAME:$CI_BUILD_REF_NAME

    wget https://github.com/arminc/clair-scanner/releases/download/v8/clair-scanner_linux_amd64
    mv clair-scanner_linux_amd64 clair-scanner
    chmod +x clair-scanner
    touch clair-whitelist.yml
    retries=0
    echo "Waiting for clair daemon to start"
    while( ! wget -T 10 -q -O /dev/null http://docker:6060/v1/namespaces ) ; do sleep 1 ; echo -n "." ; if [ $retries -eq 10 ] ; then echo " Timeout, aborting." ; exit 1 ; fi ; retries=$(($retries+1)) ; done
    ./clair-scanner -c http://docker:6060 --ip $(hostname -i) -r gl-container-scanning-report.json -l clair.log -w clair-whitelist.yml $DOCKERHUB_GROUPNAME/$CI_PROJECT_NAME:$CI_BUILD_REF_NAME || true
  }

  function setup_docker() {
    if ! docker info &>/dev/null; then
      if [ -z "$DOCKER_HOST" -a "$KUBERNETES_PORT" ]; then
        export DOCKER_HOST='tcp://localhost:2375'
      fi
    fi
  }


before_script:
  - *auto_devops
