build_docker_image: &build_docker_image
  stage: build
  image: docker:git
  services:
    - docker:dind
  before_script:
    - docker login --username=$DOCKERHUB_USER --password=$DOCKERHUB_PASSWORD
  script:
    - docker pull $DOCKERHUB_GROUPNAME/$CI_PROJECT_NAME:$CI_BUILD_REF_NAME || true
    - docker build --cache-from $DOCKERHUB_GROUPNAME/$CI_PROJECT_NAME:$CI_BUILD_REF_NAME --build-arg BUNDLE_GEMSTASH_PASSWORD=$BUNDLE_GEMSTASH_PASSWORD --build-arg env=$CI_BUILD_REF_NAME -t $CI_PROJECT_NAME:$CI_BUILD_REF .
    - docker tag $CI_PROJECT_NAME:$CI_BUILD_REF $DOCKERHUB_GROUPNAME/$CI_PROJECT_NAME:$CI_BUILD_REF_NAME
    - docker push $DOCKERHUB_GROUPNAME/$CI_PROJECT_NAME:$CI_BUILD_REF_NAME
  only:
    - stage
    - prod

manual_build_docker_image:
  <<: *build_docker_image
  only:
    - branches
  except:
    - master
    - dev
  when: manual
