build_docker_image: &build_docker_image
  stage: build
  image: docker:git
  services:
    - docker:dind
  before_script:
    - docker login --username=$DOCKERHUB_USER --password=$DOCKERHUB_PASSWORD
  script:
    - docker pull $DOCKERHUB_GROUPNAME/$CI_PROJECT_NAME:$CI_BUILD_REF_NAME || true
    - docker build --cache-from $DOCKERHUB_GROUPNAME/$CI_PROJECT_NAME:$CI_BUILD_REF_NAME --build-arg env=$CI_BUILD_REF_NAME -t $DOCKERHUB_GROUPNAME/$CI_PROJECT_NAME:$CI_BUILD_REF_NAME .
    - docker push $DOCKERHUB_GROUPNAME/$CI_PROJECT_NAME:$CI_BUILD_REF_NAME
